# Generated by Django 3.0.5 on 2020-07-19 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0007_auto_20200719_1931'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=60)),
                ('is_aprobed', models.BooleanField(default=False, verbose_name='Publicación aprobada')),
                ('business_type', models.CharField(choices=[('V', 'Venta'), ('R', 'Alquiler')], default='V', max_length=2, verbose_name='Se encuentra en')),
                ('available', models.BooleanField(default=True, verbose_name='Propiedad disponible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_property', to='data.People')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostUserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Recibir notificaciones')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección de la propiedad')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Costo de la propiedad')),
                ('lon', models.FloatField(null=True, verbose_name='Longitud geografica')),
                ('lat', models.FloatField(null=True, verbose_name='Latitud geografica')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data.City')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_detail', to='posts.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
