# Generated by Django 3.0.5 on 2020-07-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
