# Generated by Django 3.0.5 on 2020-07-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20200719_1930'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
